### PR TITLE
A: dmzj app

### PR DESCRIPTION
**Pull request by alicewww**
This is found in [dmzj app](https://apps.apple.com/cn/app/%E5%8A%A8%E6%BC%AB%E4%B9%8B%E5%AE%B6%E7%A4%BE%E5%8C%BA/id1512392614?l=en )

### CODE REVIEW

**Comment by cjx82630** [comment]
Untestable and may have unintended consequences.

**Comment by alicewww** [comment]
about untestable: you can download this app and will immediately discovered it using this domain for advertising
what do you mean by "unintended consequences"?

**Comment by cjx82630** [comment]
In addition, ELC currently does not handle app ads. ABP also has no program to block app ads. If you use ELC to block app ads, you might get unexpected results.

**Comment by alicewww** [comment]
Yes.. I'm currently using a Surge's rule set which auto-build from ELC for ads filtering in IOS. Because Surge is working as a VPN provider in IOS, it can filter ads traffic by domains.
I think this is a good point. Thanks for the explanation :)
I'll try to find a actual web page using this domain for ads when I got some time.

**Pull request closed without merging**
